name: Fly Deploy
on: 
  push: {}
  schedule:
    - cron: '5 */6 * * *'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy"
